// Image/font paths for GraphicEntityModule (generated by the SDK runner when absent).
// This game uses only vector primitives; keep maps empty unless you add files under view/assets/.
export const assets = {
  baseUrl: '',
  images: {},
  spines: {},
  sprites: [],
  fonts: [],
  others: []
}
